/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoempresariales.Vista;

import com.mycompany.proyectoempresariales.Controlador.*;
import com.mycompany.proyectoempresariales.Modelo.*;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class GUIAgregarGaseosaProveedor extends javax.swing.JFrame {

    private IGuiService guiService = GuiService.getInstance();
    private IBebidaService bebidaService = BebidaService.getInstance();
    private IProveedorService proveedorService = ProveedorService.getInstance();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIAgregarGaseosaProveedor.class.getName());

    /**
     * Creates new form GUIAgregarGaseosaProveedor
     */
    public GUIAgregarGaseosaProveedor() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoProveedor = new javax.swing.JTextField();
        txtNombreProveedor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodGaseosa = new javax.swing.JTextField();
        btnBuscarGas = new javax.swing.JButton();
        btnBuscarPro = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNombreGaseosa = new javax.swing.JTextField();
        btnAgregarGasProveedor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Agregar Proveedor");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Código:");

        txtNombreProveedor.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Codigo de Gaseosa:");

        btnBuscarGas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarGas.setText("Buscar Gaseosa");
        btnBuscarGas.setToolTipText("");
        btnBuscarGas.addActionListener(this::btnBuscarGasActionPerformed);

        btnBuscarPro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarPro.setText("Buscar Proveedor");
        btnBuscarPro.addActionListener(this::btnBuscarProActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nombre:");

        txtNombreGaseosa.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(82, 82, 82))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombreProveedor)
                                .addGap(6, 6, 6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodGaseosa, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtCodigoProveedor)
                                        .addGap(7, 7, 7))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(btnBuscarPro, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBuscarGas, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtNombreGaseosa))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarPro)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCodGaseosa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarGas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombreGaseosa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btnAgregarGasProveedor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAgregarGasProveedor.setForeground(new java.awt.Color(0, 0, 143));
        btnAgregarGasProveedor.setText("AGREGAR");
        btnAgregarGasProveedor.addActionListener(this::btnAgregarGasProveedorActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btnAgregarGasProveedor)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAgregarGasProveedor)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarGasProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarGasProveedorActionPerformed
        int Codigo = Integer.parseInt(txtCodigoProveedor.getText());
        int CodigoGaseosa = Integer.parseInt(txtCodGaseosa.getText());
        Proveedor proveedor = proveedorService.buscarProveedor(Codigo);
        Bebida bebida = bebidaService.BuscarBebida(CodigoGaseosa);
        if (proveedor == null) {
            JOptionPane.showMessageDialog(this, "Proveedor no encontrado");
            return;
        }
        if (!(bebida instanceof Gaseosa)) {
            JOptionPane.showMessageDialog(this, "La bebida no es una gaseosa");
            return;
        }
        Gaseosa gaseosa = (Gaseosa) bebida;
        txtNombreProveedor.setText(proveedor.getNombre());
        txtNombreGaseosa.setText(gaseosa.getNombre());
        try {
            proveedorService.agregarGaseosa(gaseosa, proveedor);
            JOptionPane.showMessageDialog(this, "Gaseosa Referenciada");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al agregar");
        }
    }//GEN-LAST:event_btnAgregarGasProveedorActionPerformed

    private void btnBuscarGasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarGasActionPerformed
        // TODO add your handling code here:
        int CodigoGaseosa = Integer.parseInt(txtCodGaseosa.getText());
        Bebida bebida = bebidaService.BuscarBebida(CodigoGaseosa);
        if (!(bebida instanceof Gaseosa)) {
            JOptionPane.showMessageDialog(this, "La bebida no es una gaseosa");
        }else
            txtNombreGaseosa.setText(bebida.getNombre());
        
    }//GEN-LAST:event_btnBuscarGasActionPerformed

    private void btnBuscarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProActionPerformed
        // TODO add your handling code here:
        int Codigo = Integer.parseInt(txtCodigoProveedor.getText());
       Proveedor proveedor = proveedorService.buscarProveedor(Codigo);
       if(proveedor !=null ){
           txtNombreProveedor.setText(proveedor.getNombre());
       }
       else
           JOptionPane.showMessageDialog(this, "Proveedor no Existente");
        
    }//GEN-LAST:event_btnBuscarProActionPerformed

  
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarGasProveedor;
    private javax.swing.JButton btnBuscarGas;
    private javax.swing.JButton btnBuscarPro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCodGaseosa;
    private javax.swing.JTextField txtCodigoProveedor;
    private javax.swing.JTextField txtNombreGaseosa;
    private javax.swing.JTextField txtNombreProveedor;
    // End of variables declaration//GEN-END:variables
}
