/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoempresariales.Vista;

import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class GUIPantallaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIPantallaPrincipal.class.getName());

    /**
     * Creates new form PantallaPrincipal
     */
    public GUIPantallaPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItemGaseosaAdd = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MenuItemLicorAdd = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemBuscar = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        JMenuItemPrecioVentaGaseosa = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        JMenuPrecioVentaLicores = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuTotalidad = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuBalance = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuEliminar = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenu8 = new javax.swing.JMenu();
        mAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pantalla Principal");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("ACS DISTRIBUCIONES SAS");

        jMenu1.setText("Agregar");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        MenuItemGaseosaAdd.setText("Gaseosa");
        MenuItemGaseosaAdd.addActionListener(this::MenuItemGaseosaAddActionPerformed);
        jMenu1.add(MenuItemGaseosaAdd);
        jMenu1.add(jSeparator1);

        MenuItemLicorAdd.setText("Licor");
        MenuItemLicorAdd.addActionListener(this::MenuItemLicorAddActionPerformed);
        jMenu1.add(MenuItemLicorAdd);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Busqueda");

        jMenuItemBuscar.setText("Buscar Bebida");
        jMenuItemBuscar.addActionListener(this::jMenuItemBuscarActionPerformed);
        jMenu2.add(jMenuItemBuscar);

        jMenuBar1.add(jMenu2);

        jMenu6.setText("Precios de Venta");

        JMenuItemPrecioVentaGaseosa.setText("Gaseosas");
        JMenuItemPrecioVentaGaseosa.setToolTipText("");
        JMenuItemPrecioVentaGaseosa.addActionListener(this::JMenuItemPrecioVentaGaseosaActionPerformed);
        jMenu6.add(JMenuItemPrecioVentaGaseosa);
        jMenu6.add(jSeparator4);

        JMenuPrecioVentaLicores.setText("Licores");
        JMenuPrecioVentaLicores.addActionListener(this::JMenuPrecioVentaLicoresActionPerformed);
        jMenu6.add(JMenuPrecioVentaLicores);
        jMenu6.add(jSeparator5);

        jMenuTotalidad.setText("Totalidad");
        jMenuTotalidad.addActionListener(this::jMenuTotalidadActionPerformed);
        jMenu6.add(jMenuTotalidad);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Inventario");

        jMenuBalance.setText("Mostrar Balance");
        jMenuBalance.setToolTipText("");
        jMenuBalance.addActionListener(this::jMenuBalanceActionPerformed);
        jMenu7.add(jMenuBalance);

        jMenuBar1.add(jMenu7);

        jMenu5.setText("Gestionar");

        jMenuEliminar.setText("Eliminar");
        jMenuEliminar.setToolTipText("");
        jMenuEliminar.addActionListener(this::jMenuEliminarActionPerformed);
        jMenu5.add(jMenuEliminar);
        jMenu5.add(jSeparator7);

        jMenuBar1.add(jMenu5);

        jMenu8.setText("Ayuda");

        mAcercaDe.setText("Acerca de....");
        mAcercaDe.addActionListener(this::mAcercaDeActionPerformed);
        jMenu8.add(mAcercaDe);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(308, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemGaseosaAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemGaseosaAddActionPerformed
       GUIAgregarGaseosa gui = new GUIAgregarGaseosa();
       gui.setVisible(true);
    }//GEN-LAST:event_MenuItemGaseosaAddActionPerformed

    private void jMenuItemBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBuscarActionPerformed
        GUIBuscarBebida gui = new GUIBuscarBebida();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItemBuscarActionPerformed

    private void MenuItemLicorAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemLicorAddActionPerformed
       GUIAgregarAlcoholicas gui = new GUIAgregarAlcoholicas();
       gui.setVisible(true);
    }//GEN-LAST:event_MenuItemLicorAddActionPerformed

    private void JMenuItemPrecioVentaGaseosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemPrecioVentaGaseosaActionPerformed
       GUIPrecioVentaGaseosa gui = new GUIPrecioVentaGaseosa();
       gui.setVisible(true);
    }//GEN-LAST:event_JMenuItemPrecioVentaGaseosaActionPerformed

    private void JMenuPrecioVentaLicoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuPrecioVentaLicoresActionPerformed
       GUIPrecioVentaAlcohol gui = new GUIPrecioVentaAlcohol();
       gui.setVisible(true);
    }//GEN-LAST:event_JMenuPrecioVentaLicoresActionPerformed

    private void jMenuTotalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTotalidadActionPerformed
       GUIPrecioVentaTodas gui = new GUIPrecioVentaTodas();
       gui.setVisible(true);
    }//GEN-LAST:event_jMenuTotalidadActionPerformed

    private void jMenuBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBalanceActionPerformed
        GUIMostrarBalance gui = new GUIMostrarBalance();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuBalanceActionPerformed

    private void jMenuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEliminarActionPerformed
        GUIEliminar gui = new GUIEliminar();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuEliminarActionPerformed

    private void mAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAcercaDeActionPerformed
        String AcercaDe = "Realizado por: Andres Mauricio Rubio Rios "
                + "Ana Camila Sanchez "
                + "Sebastian Torres Caleno "
                + "Version del Proyecto: Prototipo ";
        JOptionPane.showMessageDialog(this, AcercaDe);
    }//GEN-LAST:event_mAcercaDeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMenuItemPrecioVentaGaseosa;
    private javax.swing.JMenuItem JMenuPrecioVentaLicores;
    private javax.swing.JMenuItem MenuItemGaseosaAdd;
    private javax.swing.JMenuItem MenuItemLicorAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuItem jMenuBalance;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuEliminar;
    private javax.swing.JMenuItem jMenuItemBuscar;
    private javax.swing.JMenuItem jMenuTotalidad;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JMenuItem mAcercaDe;
    // End of variables declaration//GEN-END:variables
}
