/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoempresariales.Vista;

import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class GUIPantallaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIPantallaPrincipal.class.getName());

    /**
     * Creates new form PantallaPrincipal
     */
    public GUIPantallaPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        MenuItemGaseosaAdd = new javax.swing.JMenuItem();
        JMenuItemPrecioVentaGaseosa = new javax.swing.JMenuItem();
        jMenuCalcularGas = new javax.swing.JMenuItem();
        jMenuListaGas = new javax.swing.JMenuItem();
        jmenuEliminarGas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MenuItemLicorAdd = new javax.swing.JMenuItem();
        JMenuPrecioVentaLicores = new javax.swing.JMenuItem();
        jMenuCalcularLicor = new javax.swing.JMenuItem();
        jMenuListarLicor = new javax.swing.JMenuItem();
        menuEliminarLicores = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuBalance = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        mAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pantalla Principal");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("ACS DISTRIBUCIONES SAS");

        jMenu3.setText("Gaseosa");

        MenuItemGaseosaAdd.setText("Agregar Gaseosa");
        MenuItemGaseosaAdd.setToolTipText("");
        MenuItemGaseosaAdd.addActionListener(this::MenuItemGaseosaAddActionPerformed);
        jMenu3.add(MenuItemGaseosaAdd);

        JMenuItemPrecioVentaGaseosa.setText("Buscar Gaseosas");
        JMenuItemPrecioVentaGaseosa.setToolTipText("");
        JMenuItemPrecioVentaGaseosa.addActionListener(this::JMenuItemPrecioVentaGaseosaActionPerformed);
        jMenu3.add(JMenuItemPrecioVentaGaseosa);

        jMenuCalcularGas.setText("Calcular Precio");
        jMenuCalcularGas.addActionListener(this::jMenuCalcularGasActionPerformed);
        jMenu3.add(jMenuCalcularGas);

        jMenuListaGas.setText("Listar Gaseosas");
        jMenuListaGas.addActionListener(this::jMenuListaGasActionPerformed);
        jMenu3.add(jMenuListaGas);

        jmenuEliminarGas.setText("Eliminar Gaseosa");
        jmenuEliminarGas.addActionListener(this::jmenuEliminarGasActionPerformed);
        jMenu3.add(jmenuEliminarGas);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Licores");

        MenuItemLicorAdd.setText("Agregar Licor");
        MenuItemLicorAdd.addActionListener(this::MenuItemLicorAddActionPerformed);
        jMenu4.add(MenuItemLicorAdd);

        JMenuPrecioVentaLicores.setText("Buscar Licores");
        JMenuPrecioVentaLicores.addActionListener(this::JMenuPrecioVentaLicoresActionPerformed);
        jMenu4.add(JMenuPrecioVentaLicores);

        jMenuCalcularLicor.setText("Calcular Precio");
        jMenu4.add(jMenuCalcularLicor);

        jMenuListarLicor.setText("Listar Licores");
        jMenu4.add(jMenuListarLicor);

        menuEliminarLicores.setText("Eliminar Licores");
        jMenu4.add(menuEliminarLicores);

        jMenuBar1.add(jMenu4);

        jMenu7.setText("Inventario");

        jMenuBalance.setText("Mostrar Balance");
        jMenuBalance.setToolTipText("");
        jMenuBalance.addActionListener(this::jMenuBalanceActionPerformed);
        jMenu7.add(jMenuBalance);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Ayuda");

        mAcercaDe.setText("Acerca de....");
        mAcercaDe.addActionListener(this::mAcercaDeActionPerformed);
        jMenu8.add(mAcercaDe);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(308, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemGaseosaAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemGaseosaAddActionPerformed
       GUIAgregarGaseosa gui = new GUIAgregarGaseosa();
       gui.setVisible(true);
    }//GEN-LAST:event_MenuItemGaseosaAddActionPerformed

    private void MenuItemLicorAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemLicorAddActionPerformed
       GUIAgregarAlcoholicas gui = new GUIAgregarAlcoholicas();
       gui.setVisible(true);
    }//GEN-LAST:event_MenuItemLicorAddActionPerformed

    private void JMenuItemPrecioVentaGaseosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemPrecioVentaGaseosaActionPerformed
       GUIBuscarGaseosa gui = new GUIBuscarGaseosa();
       gui.setVisible(true);
    }//GEN-LAST:event_JMenuItemPrecioVentaGaseosaActionPerformed

    private void JMenuPrecioVentaLicoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuPrecioVentaLicoresActionPerformed
       //GUIPrecioVentaAlcohol gui = new GUIPrecioVentaAlcohol();
      // gui.setVisible(true);
    }//GEN-LAST:event_JMenuPrecioVentaLicoresActionPerformed

    private void jMenuBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBalanceActionPerformed
        GUIMostrarBalance gui = new GUIMostrarBalance();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuBalanceActionPerformed

    private void mAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAcercaDeActionPerformed
        String AcercaDe = "Realizado por: Andres Mauricio Rubio Rios "
                + "Ana Camila Sanchez "
                + "Sebastian Torres Caleno "
                + "Version del Proyecto: Prototipo ";
        JOptionPane.showMessageDialog(this, AcercaDe);
    }//GEN-LAST:event_mAcercaDeActionPerformed

    private void jMenuCalcularGasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCalcularGasActionPerformed
        // TODO add your handling code here:
        GUIPrecioVentaGaseosa gui = new GUIPrecioVentaGaseosa();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuCalcularGasActionPerformed

    private void jmenuEliminarGasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuEliminarGasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmenuEliminarGasActionPerformed

    private void jMenuListaGasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListaGasActionPerformed
        GUIGridGaseosas gui = new GUIGridGaseosas();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuListaGasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMenuItemPrecioVentaGaseosa;
    private javax.swing.JMenuItem JMenuPrecioVentaLicores;
    private javax.swing.JMenuItem MenuItemGaseosaAdd;
    private javax.swing.JMenuItem MenuItemLicorAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuItem jMenuBalance;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCalcularGas;
    private javax.swing.JMenuItem jMenuCalcularLicor;
    private javax.swing.JMenuItem jMenuListaGas;
    private javax.swing.JMenuItem jMenuListarLicor;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JMenuItem jmenuEliminarGas;
    private javax.swing.JMenuItem mAcercaDe;
    private javax.swing.JMenuItem menuEliminarLicores;
    // End of variables declaration//GEN-END:variables
}
